export const skills = [
  { 
    title: 'HTML',
    icon: 'https://ik.imagekit.io/twsok8jou/html.svg',
    type: 'front-end',
    height: 49,
    width: 35,
    rating: 90,
  },
  { 
    title: 'CSS',
    icon: 'https://ik.imagekit.io/twsok8jou/css.svg',
    type: 'front-end',
    height: 49,
    width: 35,
    rating: 85,
  },
  { 
    title: 'Javascript',
    icon: 'https://ik.imagekit.io/twsok8jou/javascript.svg',
    type: 'front-end',
    height: 49,
    width: 35,
    rating: 90,
  },
  { 
    title: 'Typescript',
    icon: 'https://ik.imagekit.io/twsok8jou/typescript.svg',
    type: 'front-end',
    height: 49,
    width: 40,
    rating: 75,
  },
  { 
    title: 'React',
    icon: 'https://ik.imagekit.io/twsok8jou/react.svg',
    type: 'front-end',
    height: 49,
    width: 45,
    rating: 90,
  },
  {
    title: 'NextJS',
    icon: 'https://ik.imagekit.io/twsok8jou/nextjs-icon.svg',
    type: 'front-end',
    height: 49,
    width: 40,
    rating: 75
  },
  {
    title: 'NodeJS',
    icon: 'https://ik.imagekit.io/twsok8jou/nodejs.svg',
    type: 'back-end',
    height: 40,
    width: 55,
    rating: 80,
  },
  {
    title: 'Python',
    icon: 'https://ik.imagekit.io/twsok8jou/python.svg',
    type: 'back-end',
    height: 35,
    width: 35,
    rating: 75,
  },
  {
    title: 'Express',
    icon: 'https://ik.imagekit.io/twsok8jou/icons8-express-js.svg',
    type: 'back-end',
    height: 49,
    width: 35,
    rating: 80,
  },
  {
    title: 'Flask',
    icon: 'https://ik.imagekit.io/twsok8jou/flask.svg',
    type: 'back-end',
    height: 40,
    width: 29,
    rating: 70,
  },
  {
    title: 'MongoDB',
    icon: 'https://ik.imagekit.io/twsok8jou/mongodb.svg',
    type: 'back-end',
    height: 50,
    width: 50,
    rating: 80,
  },
  {
    title: 'Postman',
    icon: 'https://ik.imagekit.io/twsok8jou/postman.svg',
    type: 'back-end',
    height: 35,
    width: 35,
    rating: 70,
  },
  {
    title: 'Docker',
    icon: 'https://ik.imagekit.io/twsok8jou/docker.svg',
    type: 'devops-cloud',
    height: 50,
    width: 50,
    rating: 85
  },
  {
    title: 'Jenkins',
    icon: 'https://ik.imagekit.io/twsok8jou/jenkins.svg',
    type: 'devops-cloud',
    height: 50,
    width: 40,
    rating: 60,
    show: false,
  },
  {
    title: 'Cloud',
    icon: 'https://ik.imagekit.io/twsok8jou/aws.svg',
    type: 'devops-cloud',
    height: 35,
    width: 50,
    rating: 60,
    show: false,
  },
]